### PR TITLE
fix "Nested quantifiers in regex" error on perl 5.8.x

### PR DESCRIPTION
**Pull request by karenetheridge**
closes issue #11 

All tests pass, but please confirm that I did not change the intention of the regex!

### CODE REVIEW

**Comment by karenetheridge** [comment]
*waves from the 2017 Toolchain Summit*

**Comment by Grinnz** [comment]
To preserve the possessive quantifier, `(?:\\?+.)` could be changed to `(?:(?>\\?).)`

**Comment by karenetheridge** [comment]
commit amended as per Grinnz's suggestion.

**Comment by karenetheridge** [comment]
♥︎♥︎♥︎👯💃🏼👯‍♂️🕺💃🏼

**Pull request merged**
