### PR TITLE
Fixes for "perl in space"

### PR DESCRIPTION
**Pull request by mohawk2**

### CODE REVIEW

**Comment by karenetheridge** [comment]
is it possible to add a test that covers this case?

**Comment by garu** [comment]
@mohawk2 thanks for the PR. Could you please update it so it merges properly? Also, as @karenetheridge said, it would be great if you could provide a test case for this too.

Thanks! Let me know if I can help :)

**Comment by mohawk2** [comment]
The test I have added failed on the code without my change, and passed on it.

By the way, your CPAN latest version is 0.10, but the `$VERSION` in `lib/CPAN/Testers/Common/Client.pm` is still at 0.08. Possibly an error?

**Comment by garu** [comment]
Thanks, @mohawk2!

Sorry for taking so long to reply, I was only able to get around to it now at the QA Hackathon. You're right about the $VERSION number, I was just bad at updating the repo. It's fixed now :)

Your idea is sound, and I merged your patch to keep your commit, but I'll have to fiddle a bit with the patch itself. See, `id_file` could be more than just the filename. It could be a relative path (e.g. ~/foo/file) or even a complete path (`/some path/file`), and the way it was implemented did not account for that bit. Second, Metabase is not the only transport mechanism, and we need the fix to work for all other transports.

I talked to @rjbs about this and what we're doing instead is: if you have spaces in your attributes, put them under double quotes. And we're always adding the double quotes to metabase paths, this way it will (hopefully) work as expected, turning:

`metabase_id.json`

into:

`"/my long path/to/the/file/called/metabase_id.json"`

Commit ce1b3d1573b267c98c5b02814e4b5211bcc214b9 completely fixes the issue. Thanks again and please let us know if you bump into any problems :)

**Pull request merged**
